Countries = [
          #http://travelerscenturyclub.org/countries-and-territories/alphabetical-list
          "Abkhazia",
          "Abu Dhabi",
          "Admiralty Islands ",
          "Afghanistan",
          "Agalega ",
          "Aitutaki ",
          "Ajman",
          "Aland Islands ",
          "Alaska",
          "Albania",
          "Aldabra ",
          "Alderney ",
          "Algeria",
          "Amirante Island ",
          "Amsterdam",
          "Anatolia ",
          "Andaman-Nicobar Islands",
          "Andorra",
          "Angola",
          "Anguilla",
          "Anjouan ",
          "Ankara ",
          "Antigua & Deps. ",
          "Argentina",
          "Argentine Antarctica ",
          "Armenia ",
          "Aruba",
          "Ascension",
          "Atafu ",
          "Austral ",
          "Australia",
          "Australian Antarctic Territory South Pole ",
          "Austria",
          "Azerbaijan ",
          "Azores Islands",
          "Bahamas",
          "Bahrain",
          "Balearic Islands ",
          "Bali ",
          "Bangladesh",
          "Barbados",
          "Barbuda",
          "Basutoland ",
          "Bear Island ",
          "Bechuanaland ",
          "Belarus",
          "Belgium",
          "Belize ",
          "Benin ",
          "Bequia ",
          "Bermuda",
          "Bhutan",
          "Bismark Archipelago ",
          "Bolivia",
          "Bonaire",
          "Bonin ",
          "Bosnia & Herzegovina ",
          "Botswana ",
          "Bougainville ",
          "Bouvet ",
          "Brazil",
          "Brazzaville ",
          "British Antarctica ",
          "British Guiana ",
          "British Honduras ",
          "British Indian Ocean Territory ",
          "British Somaliland ",
          "British Togoland ",
          "Brunei",
          "Bulgaria",
          "Burkina Faso ",
          "Burma ",
          "Burundi ",
          "Cabinda",
          "Caicos ",
          "Cambodia",
          "Cameroon",
          "Canada",
          "Canary Islands",
          "Canouan ",
          "Canton ",
          "Cape Verde Islands",
          "Caroline Islands ",
          "Carriacou ",
          "Cayman Islands",
          "Celebes",
          "Central African Republic",
          "Ceuta ",
          "Ceylon ",
          "Chad",
          "Chagos Archipeloago ",
          "Channel Islands ",
          "Chile",
          "Chilean Antarctica ",
          "China, People’s Republic of",
          "Christmas Island ",
          "Christmas Island ",
          "Chuuk ",
          "Cocos Islands ",
          "Colombia",
          "Comoro Islands ",
          "Congo, Democratic Republic of ",
          "Congo, Republic of ",
          "Cook Islands ",
          "Corfu ",
          "Corsica",
          "Costa Rica",
          "Crete",
          "Croatia",
          "Crozet ",
          "Cuba",
          "Curacao",
          "Cyprus, Republic of",
          "Cyprus, Turkish Fed. State of",
          "Czech Republic"]