Countries = [
          #http://travelerscenturyclub.org/countries-and-territories/alphabetical-list
          "Abkhazia",
          "Abu Dhabi",
          "Admiralty Islands ",
          "Afghanistan",
          "Agalega ",
          "Aitutaki ",
          "Ajman",
          "Aland Islands ",
          "Alaska",
          "Albania",
          "Aldabra ",
          "Alderney ",
          "Algeria",
          "Amirante Island ",
          "Amsterdam",
          "Anatolia ",
          "Andaman-Nicobar Islands",
          "Andorra",
          "Angola",
          "Anguilla",
          "Anjouan ",
          "Ankara ",
          "Antigua & Deps. ",
          "Argentina",
          "Argentine Antarctica ",
          "Armenia ",
          "Aruba",
          "Ascension",
          "Atafu ",
          "Austral ",
          "Australia",
          "Australian Antarctic Territory South Pole ",
          "Austria",
          "Azerbaijan ",
          "Azores Islands",
          "Bahamas",
          "Bahrain",
          "Balearic Islands ",
          "Bali ",
          "Bangladesh",
          "Barbados",
          "Barbuda",
          "Basutoland ",
          "Bear Island ",
          "Bechuanaland ",
          "Belarus",
          "Belgium",
          "Belize ",
          "Benin ",
          "Bequia ",
          "Bermuda",
          "Bhutan",
          "Bismark Archipelago ",
          "Bolivia",
          "Bonaire",
          "Bonin ",
          "Bosnia & Herzegovina ",
          "Botswana ",
          "Bougainville ",
          "Bouvet ",
          "Brazil",
          "Brazzaville ",
          "British Antarctica ",
          "British Guiana ",
          "British Honduras ",
          "British Indian Ocean Territory ",
          "British Somaliland ",
          "British Togoland ",
          "Brunei",
          "Bulgaria",
          "Burkina Faso ",
          "Burma ",
          "Burundi ",
          "Cabinda",
          "Caicos ",
          "Cambodia",
          "Cameroon",
          "Canada",
          "Canary Islands",
          "Canouan ",
          "Canton ",
          "Cape Verde Islands",
          "Caroline Islands ",
          "Carriacou ",
          "Cayman Islands",
          "Celebes",
          "Central African Republic",
          "Ceuta ",
          "Ceylon ",
          "Chad",
          "Chagos Archipeloago ",
          "Channel Islands ",
          "Chile",
          "Chilean Antarctica ",
          "China, People’s Republic of",
          "Christmas Island ",
          "Christmas Island ",
          "Chuuk ",
          "Cocos Islands ",
          "Colombia",
          "Comoro Islands ",
          "Congo, Democratic Republic of ",
          "Congo, Republic of ",
          "Cook Islands ",
          "Corfu ",
          "Corsica",
          "Costa Rica",
          "Crete",
          "Croatia",
          "Crozet ",
          "Cuba",
          "Curacao",
          "Cyprus, Republic of",
          "Cyprus, Turkish Fed. State of",
          "Czech Republic",
          "Dahomey ",
          "Davis ",
          "Denmark",
          "Diego Garcia ",
          "Djibouti",
          "Dodecanese Islands ",
          "Dominica",
          "Dominican Republic",
          "Dubai",
          "Dzaoudzi ",
          "Easter Island",
          "Ecuador",
          "Eire ",
          "Egypt in Africa",
          "Egypt in Asia ",
          "El Salvador",
          "Ellice Islands ",
          "Enderbury ",
          "England",
          "Eniwetok ",
          "Equatorial Guinea ",
          "Equatorial Guinea ",
          "Eritrea",
          "Estonia",
          "Ethiopia",
          "Fakaofu ",
          "Falkland Islands",
          "Falkland Islands Dependencies ",
          "Fanning ",
          "Faroe Islands",
          "Farquhar ",
          "Fernando do Noronha",
          "Fernando Poo ",
          "Fiji Islands",
          "Finland",
          "France",
          "French Guiana",
          "French Guinea",
          "French Polynesia ",
          "French Southern & Antarctic Territory ",
          "Fujeirah",
          "Funafuti ",
          "Futuna ",
          "Gabon",
          "Galapagos Islands",
          "Gambia",
          "Gambier ",
          "Georgia",
          "Germany",
          "Ghana ",
          "Gibraltar",
          "Gilberts ",
          "Glorioso ",
          "Gold Coast ",
          "Graham Land ",
          "Grand Comoro ",
          "Greece",
          "Greenland ",
          "Grenada & Deps. ",
          "Grenadines ",
          "Guadalcanal",
          "Guadeloupe & Deps.",
          "Margarita Island ",
          "Guam",
          "Guatemala",
          "Guernsey & Deps. ",
          "Guiana ",
          "Guinea ",
          "Guinea-Bissau",
          "Guyana ",
          "Hainan Island",
          "Haiti",
          "Hawaiian Islands",
          "Heard ",
          "Herm ",
          "Herzegovina ",
          "Honduras",
          "Hong Kong",
          "Howland ",
          "Hungary",
          "Iceland",
          "India",
          "Indonesia",
          "Indonesian Borneo ",
          "Ionian Islands ",
          "Iran",
          "Iraq",
          "Ireland, Republic of ",
          "Ireland, Northern ",
          "Isle of Man",
          "Israel",
          "Istanbul ",
          "Italian Somaliland ",
          "Italy",
          "Ivory Coast",
          "Iwo Jima ",
          "Izmir ",
          "Jamaica",
          "Japan",
          "Java",
          "Jeju Island ",
          "Jersey ",
          "Jordan",
          "Juan Fernandez Islands ",
          "Kalaallit Nunaat ",
          "Kalimantan ",
          "Kaliningrad",
          "Kashmir",
          "Kazakhstan",
          "Keeling ",
          "Kenya",
          "Kerguelen ",
          "Kinshasa ",
          "Kiribati ",
          "Korea, North ",
          "Korea, South ",
          "Kosovo",
          "Kosrae ",
          "Kuwait",
          "Kwajalein ",
          "Kyrgyzstan",
          "Lakshadweep",
          "Lampedusa",
          "Laos",
          "Latvia",
          "Lebanon",
          "Leeward Islands, French ",
          "Leeward Islands, Netherlands ",
          "Lesotho ",
          "Lesser Sunda Islands ",
          "Liberia",
          "Libya",
          "Liechtenstein",
          "Line/Phoenix Islands ",
          "Lithuania",
          "Lord Howe Island",
          "Loyalty Islands ",
          "Luxembourg",
          "Macau",
          "Macedonia",
          "Macquarie ",
          "Madagascar",
          "Madeira",
          "Majuro ",
          "Malawi ",
          "Malaysia",
          "Maldive Islands",
          "Mali",
          "Mallorca ",
          "Malta",
          "Marie Galante ",
          "Mariehamn ",
          "Marquesas Islands",
          "Marshall Islands, Republic of ",
          "Martinique",
          "Mauritania",
          "Mauritius & Deps. ",
          "Mawson ",
          "Mayotte ",
          "Melilla ",
          "Mexico",
          "Micronesia, Fed.States of ",
          "Midway Island",
          "Minorca ",
          "Miquelon ",
          "Moheli ",
          "Moldova",
          "Moluka",
          "Monaco",
          "Mongolia, Rep.",
          "Montenegro",
          "Montserrat",
          "Morocco, Kingdom of",
          "Morocco,Spanish ",
          "Mozambique",
          "Myanmar ",
          "Nakhchivan",
          "Namibia",
          "Nauru",
          "Nepal",
          "Netherlands",
          "Netherlands Antilles ",
          "Netherlands Guiana ",
          "Nevis ",
          "New Britain ",
          "New Caledonia & Deps. ",
          "Nueva Esparta ",
          "New Georgia ",
          "New Hebrides Islands ",
          "New Ireland ",
          "New Zealand",
          "New Zealand Antarctica ",
          "Nicaragua",
          "Nicobar Islands ",
          "Niger",
          "Nigeria",
          "Niue",
          "Norfolk Island",
          "North Borneo ",
          "Northern Marianas ",
          "Northern Rhodesia ",
          "Norway",
          "Norwegian Antarctica ",
          "Noumea ",
          "Nukualofa",
          "Nunaat",
          "Nyasaland ",
          "Ocean Island ",
          "Ogasawara ",
          "Okinawa ",
          "Oman",
          "Pago Pago ",
          "Pakistan",
          "Palau, Republic of",
          "Palestine",
          "Palmer Peninsula ",
          "Palmyra ",
          "Panama",
          "Papua ",
          "Papua New Guinea",
          "Paraguay",
          "Penrhyn ",
          "Peru",
          "Philippines",
          "Phoenix/Line Islands ",
          "Pitcairn Island",
          "Pohnpei ",
          "Poland",
          "Portugal",
          "Prince Edward Island",
          "Principe ",
          "Providencia ",
          "Puerto Rico",
          "Qatar",
          "Queen Maud Land ",
          "Rarotonga",
          "Ras Al Khaimah",
          "Redonda ",
          "Reunion & Deps. ",
          "Rhodes ",
          "Rio Muni ",
          "Robinson Crusoe Island ",
          "Rodriguez Island",
          "Romania",
          "Ross Dependency ",
          "Russia",
          "Russia in Asia ",
          "Rwanda",
          "Ryukyu Islands ",
          "Saba ",
          "Sabah ",
          "Saipan ",
          "Samoa ",
          "Samoa, American ",
          "San Andres & Providencia",
          "San Marino",
          "Sao Tome & Principe",
          "Sarajevo ",
          "Sarawak",
          "Sardinia",
          "Sark ",
          "Saudi Arabia",
          "Scotland",
          "Senegal",
          "Serbia",
          "Seychelles",
          "Sharjah",
          "Siberia ",
          "Sicily",
          "Sierra Leone",
          "Sikkim",
          "Singapore",
          "Slovakia",
          "Slovenia",
          "Socotra",
          "Solomon Islands ",
          "Somalia ",
          "Somaliland ",
          "South Africa",
          "South Georgia ",
          "South Orkney ",
          "South Sandwich ",
          "South Sudan",
          "South Shetland ",
          "Southern Rhodesia ",
          "Spain",
          "Spanish Sahara ",
          "Spitsbergen ",
          "Sri Lanka ",
          "Srpska",
          "St. Barts",
          "St. Brandon ",
          "St. Croix",
          "St. Eustatius ",
          "St. Helena",
          "St. John ",
          "St. Kitts & Nevis",
          "St. Lucia",
          "St. Maarten ",
          "St. Martin ",
          "St. Paul ",
          "St. Pierre & Miquelon",
          "St. Thomas ",
          "St. Vincent & Deps. ",
          "Sudan",
          "Sulawesi ",
          "Sumatra ",
          "Suriname ",
          "Svalbard ",
          "Swaziland",
          "Sweden",
          "Switzerland",
          "Syria",
          "Tahiti ",
          "Taiwan. R.O.C.",
          "Tajikistan",
          "Tanganyika ",
          "Tanzania ",
          "Tarawa ",
          "Tasmania",
          "Thailand",
          "Tibet",
          "Timor, Indonesia ",
          "Timor Leste",
          "Tinian ",
          "Tobago ",
          "Togo",
          "Tokelau Islands ",
          "Tonga ",
          "Tortola ",
          "Trans Dniester",
          "Trinidad & Tobago",
          "Tristan da Cunha",
          "Tromelin ",
          "Tuamotu ",
          "Tulagi ",
          "Tunisia",
          "Turkey in Asia ",
          "Turkey in Europe ",
          "Turkmenistan",
          "Turks & Caicos Islands",
          "Tuvalu ",
          "Uganda",
          "Ukraine",
          "Ulster ",
          "Umm Al Qaiwain",
          "Union Island ",
          "United States ",
          "Upper Volta ",
          "Uruguay",
          "Urundi ",
          "Uzbekistan",
          "Vaitapu ",
          "Vanuatu ",
          "Vatican City",
          "Venezuela",
          "Vietnam",
          "Virgin Islands, British ",
          "Virgin Islands, U.S. ",
          "Volcano Island ",
          "Wake Island",
          "Wales",
          "Wallis & Futuna Islands",
          "Western Sahara ",
          "Yap ",
          "Yemen",
          "Yerevan ",
          "Zambia ",
          "Zanzibar",
          "Zil Elwannyen Sesel ",
          "Zimbabwe "]